In [115]:
# 1.1 calcul du plus court chemin entre deux sommmets d'un graphe
# Input: Graph G (adjacency matrix), source vertex s
# Output: Shortest distance to all vertices from s

function BellmanFord(G, s)
    nbv = size(A)[1]
    # dans chaque ligne i  
    # dis[i, 1] correspond au cout min entre s et le noeud i 
    # dis[i, 2] correspond au predecesseur par lequel on trouve le cout min
    dis = zeros(nbv, 2) 
    
    for i in 1:nbv
        dis[i, 1] = Inf
        dis[i, 2] = -1
    end
    dis[s, 1] = 0
    
    for k in 1:(nbv - 1)
        # edge (i, j)
        for i in 1:nbv
            for j in 1:nbv
                if (G[i, j] != 0) && (dis[j, 1] > (dis[i, 1] + G[i, j]))
                    dis[j, 1] = dis[i, 1] + G[i,j]
                    dis[j, 2] = i
                    println(dis)
                end
            end
        end
    end
    return dis
end


    

BellmanFord (generic function with 2 methods)

In [116]:
function affres(dis, s, d)
    j = d
    while j != s 
        a = Int(dis[j, 2])
        println("On va de $j à $a")
        j = a
    end
end

affres (generic function with 1 method)

In [117]:
G = [0 3 0 0 5 0;
     0 0 4 0 0 0;
     0 0 0 2 0 0;
     0 0 0 0 0 3;
     0 (-1) 0 9 0 0;
     0 0 0 0 0 0]
dis = BellmanFord(G, 1)
affres(dis, 1, 6)

[0.0 -1.0; 3.0 1.0; Inf -1.0; Inf -1.0; Inf -1.0; Inf -1.0]
[0.0 -1.0; 3.0 1.0; Inf -1.0; Inf -1.0; 5.0 1.0; Inf -1.0]
[0.0 -1.0; 3.0 1.0; 7.0 2.0; Inf -1.0; 5.0 1.0; Inf -1.0]
[0.0 -1.0; 3.0 1.0; 7.0 2.0; 9.0 3.0; 5.0 1.0; Inf -1.0]
[0.0 -1.0; 3.0 1.0; 7.0 2.0; 9.0 3.0; 5.0 1.0; 12.0 4.0]
On va de 6 à 4
On va de 4 à 3
On va de 3 à 2
On va de 2 à 1


In [122]:
# 1.1 calcul du plus court chemin entre deux sommmets d'un graphe
# Input: Graph G (adjacency matrix), source vertex s
# Output: Shortest distance to all vertices from s

function BellmanFord2(G, s)
    G = 
    return BellmanFord(,s)
end

BellmanFord2 (generic function with 1 method)

In [125]:
G = [0 3 0 0 5 0;
     0 0 4 0 0 0;
     0 0 0 2 0 0;
     0 0 0 0 0 3;
     0 (-1) 0 9 0 0;
     0 0 0 0 0 0]
dis = BellmanFord2(G, 1)


6×2 Array{Float64,2}:
  0.0  -1.0
 Inf   -1.0
 Inf   -1.0
 Inf   -1.0
 Inf   -1.0
 Inf   -1.0

In [25]:
A = [0 3 0 0 5 0;
     0 0 4 0 0 0;
     0 0 0 2 0 0;
     0 0 0 0 0 3;
     0 (-1) 0 9 0 0;
     0 0 0 0 0 0]

6×6 Array{Int64,2}:
 0   3  0  0  5  0
 0   0  4  0  0  0
 0   0  0  2  0  0
 0   0  0  0  0  3
 0  -1  0  9  0  0
 0   0  0  0  0  0

In [124]:
A = zeros(size(A))

6×6 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

In [28]:
dis = zeros(1,6)

1×6 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0

In [49]:
dis = zeros(6, 2)

6×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [58]:
    for i in 1:nbv
        dis[i, 1] = Inf
        dis[i, 2] = -1
    end

In [64]:
dis

6×2 Array{Float64,2}:
 Inf  -1.0
 Inf  -1.0
 Inf  -1.0
 Inf  -1.0
 Inf  -1.0
 Inf  -1.0

In [69]:
G[1,2]

3

In [70]:
(dis[2, 1] > (dis[1, 1] + G[1,2]))

false