In [53]:
# 1.1 calcul du plus court chemin entre deux sommmets d'un graphe
# Input: Graph G (adjacency matrix), source vertex s
function BellmanFord(G, s)
    nbv = size(G)[1]
    # dans chaque ligne i  
    # dis[i, 1] correspond au cout min entre s et le noeud i 
    # dis[i, 2] correspond au predecesseur par lequel on trouve le cout min
    dis = zeros(nbv, 2) 
    
    for i in 1:nbv
        dis[i, 1] = Inf
        dis[i, 2] = -1
    end
    dis[s, 1] = 0
    
    for k in 1:(nbv - 1)
        # edge (i, j)
        for i in 1:nbv
            for j in 1:nbv
                if (G[i, j] != 0) && (dis[j, 1] > (dis[i, 1] + G[i, j]))
                    dis[j, 1] = dis[i, 1] + G[i,j]
                    dis[j, 2] = i
                end
            end
        end
    end
    return dis
end    

BellmanFord (generic function with 1 method)

In [54]:
function affres(dis, s, d)
    j = d
    while j != s 
        a = Int(dis[j, 2])
        println("On va de $j à $a")
        j = a
    end
end

affres (generic function with 1 method)

In [55]:
G = [0 3 0 0 5 0;
     0 0 4 0 0 0;
     0 0 0 2 0 0;
     0 0 0 0 0 3;
     0 (-1) 0 9 0 0;
     0 0 0 0 0 0]
dis = BellmanFord(G, 1)
affres(dis, 1, 6)

On va de 6 à 4
On va de 4 à 3
On va de 3 à 2
On va de 2 à 1


In [56]:
G1 = [0 (-1) 4 0 0;
      0 0 3 2 2;
      0 0 0 0 0;
      0 1 5 0 0;
      0 0 0 (-3) 0]
dis2 = BellmanFord(G1, 1)

5×2 Array{Float64,2}:
  0.0  -1.0
 -1.0   1.0
  2.0   2.0
 -2.0   5.0
  1.0   2.0

In [58]:
# 1.2 calcul du plus long chemin entre deux sommmets d'un graphe
# Input: Graph G (adjacency matrix), source vertex s
function BellmanFord2(G, s)
    nbv = size(G)[1]
    # dans chaque ligne i  
    # dis[i, 1] correspond au cout min entre s et le noeud i 
    # dis[i, 2] correspond au predecesseur par lequel on trouve le cout min
    dis = zeros(nbv, 2) 
    
    for i in 1:nbv
        dis[i, 1] = -Inf
        dis[i, 2] = -1
    end
    dis[s, 1] = 0
    
    for k in 1:(nbv - 1)
        # edge (i, j)
        for i in 1:nbv
            for j in 1:nbv
                if (G[i, j] != 0) && (dis[j, 1] < (dis[i, 1] + G[i, j]))
                    dis[j, 1] = dis[i, 1] + G[i,j]
                    dis[j, 2] = i
                end
            end
        end
    end
    return dis
end

BellmanFord2 (generic function with 1 method)

In [59]:
G = [0 3 0 0 5 0;
     0 0 4 0 0 0;
     0 0 0 2 0 0;
     0 0 0 0 0 3;
     0 (-1) 0 9 0 0;
     0 0 0 0 0 0]
dis = BellmanFord2(G, 1)
affres(dis, 1, 6)

On va de 6 à 4
On va de 4 à 5
On va de 5 à 1


In [60]:
G1 = [0 (-1) 4 0 0;
      0 0 3 2 2;
      0 0 0 0 0;
      0 1 5 0 0;
      0 0 0 (-3) 0]
dis2 = BellmanFord2(G1, 1)

5×2 Array{Float64,2}:
  0.0  -1.0
 11.0   4.0
 15.0   4.0
 10.0   2.0
 10.0   2.0

In [91]:
# 2.1 calculer le chemin de vitesse max entre deux sommet d'un graphe
# Input: Graph G (adjacency matrix), source vertex s
# Output: path that maximises speed to all vertices from s
function BellmanFord3(G, s)
    nbv = size(G)[1]
    # dans chaque ligne i  
    # vts[i, 1] correspond au vmin entre s et le noeud i 
    # vts[i, 2] correspond au predecesseur par lequel on trouve le chemin qui maximise vmin
    vts = zeros(nbv, 2) 
    for i in 1:nbv
        vts[i, 1] = 0
        vts[i, 2] = -1
    end
    vts[s, 1] = Inf
    
    for k in 1:(nbv - 1)
        # edge (i, j)
        for i in 1:nbv
            for j in 1:nbv
                if (G[i, j] != 0) && (vts[i, 1] > vts[j, 1])
                    if (vts[j, 1] != Inf) && (vts[j, 1] > G[i, j])
                        vts[j, 1] = G[i, j]
                    end
                    vts[j, 1] = vts[i, 1]
                    vts[j, 2] = i
                end
            end
        end
    end
    return vts
end    

BellmanFord3 (generic function with 1 method)

In [92]:
P = [   0 5 0 0 1 0 3; 
        5 0 4 0 0 0 0;
        0 4 0 1 2 2 0; 
        0 0 1 0 0 2 0; 
        1 0 2 0 0 3 5; 
        0 0 2 2 3 0 0; 
        3 0 0 0 5 0 0]
vts = BellmanFord3(P, 1)


7×2 Array{Float64,2}:
 Inf  -1.0
 Inf   1.0
 Inf   2.0
 Inf   3.0
 Inf   1.0
 Inf   3.0
 Inf   1.0

In [124]:
A = zeros(size(A))

6×6 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

In [28]:
dis = zeros(1,6)

1×6 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0

In [49]:
dis = zeros(6, 2)

6×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [58]:
    for i in 1:nbv
        dis[i, 1] = Inf
        dis[i, 2] = -1
    end

In [64]:
dis

6×2 Array{Float64,2}:
 Inf  -1.0
 Inf  -1.0
 Inf  -1.0
 Inf  -1.0
 Inf  -1.0
 Inf  -1.0

In [69]:
G[1,2]

3

In [70]:
(dis[2, 1] > (dis[1, 1] + G[1,2]))

false